name: Python Bindings
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  check_relevant_changes:
    runs-on: ubuntu-latest
    outputs:
      continue_run: ${{ steps.check.outputs.continue_run }}
    env:
      IGNORED_FOLDERS: "rko_lio/ros|tests/core|cmake/dependencies/catch2|docs|launch|config"
      IGNORED_FILES: "colcon.pkg|package.xml|rosdoc2.yaml|CHANGELOG.rst|LICENSE|README.md"
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - id: check
        run: |
          changed_files=$(git diff --name-only origin/master)
          echo "Changed files: $changed_files"
          if echo "$changed_files" | grep -vE "^($IGNORED_FOLDERS)/|^($IGNORED_FILES)$" > /dev/null; then
            echo "continue_run=true" >> $GITHUB_OUTPUT
          else
            echo "continue_run=false" >> $GITHUB_OUTPUT
          fi
  python_bindings:
    needs: check_relevant_changes
    if: needs.check_relevant_changes.outputs.continue_run == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-14
          - macos-15
          - windows-2022
    env:
      GIT_LFS_SKIP_SMUDGE: 1
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python3
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Build with pip
        run: python -m pip install --verbose . pytest
      - name: Run pytest
        run: pytest -v -rs
  python_bindings_optional:
    needs: check_relevant_changes
    if: needs.check_relevant_changes.outputs.continue_run == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-14
          - macos-15
          - windows-2022
    env:
      GIT_LFS_SKIP_SMUDGE: 1
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python3
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install package with optional dependencies
        run: python -m pip install --verbose ".[all]" pytest
      - name: Run pytest with optional dependency tests
        run: pytest -v -rs
